<?php

return [
    'jobs' => [
        [
            'title' => 'currency:fetch-rates',
            'command' => 'currency:fetch-rates',
            'args' => [],
            'description' => 'Fetches latest USD/INR currency exchange rates via Frankfurt API.',
            'schedule' => 'Daily at 20:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync',
            'command' => 'equities:sync',
            'args' => [],
            'description' => 'Syncs equity OHLCV price data from NSE/BSE.',
            'schedule' => 'Daily at 19:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'indices:sync',
            'command' => 'indices:sync',
            'args' => [],
            'description' => 'Syncs market index prices, overview data, and holdings.',
            'schedule' => 'Daily at 19:15; maintenance refreshes can also run manually',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'sync:mf-daily',
            'command' => 'sync:mf-daily',
            'args' => ['--force' => true, '--skip-returns' => true],
            'description' => 'Syncs mutual fund NAVs in the first publication window.',
            'schedule' => 'Daily at 21:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'mf:sync',
            'command' => 'mf:sync',
            'args' => ['--force' => true],
            'description' => 'Runs the mutual fund NAV synchronization manually or from another command.',
            'schedule' => 'Manual / invoked by orchestrators',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'mf:sync-and-calculate',
            'command' => 'mf:sync-and-calculate',
            'args' => [],
            'description' => 'Syncs mutual fund NAVs and computes performance returns.',
            'schedule' => 'Daily at 23:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'mf:sync-upstox-daily',
            'command' => 'mf:sync-upstox-daily',
            'args' => [],
            'description' => 'Imports the latest Upstox mutual-fund rates as an independent AMFI fallback and computes returns.',
            'schedule' => 'Daily at 06:10',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'mf:backfill',
            'command' => 'mf:backfill',
            'args' => ['--from' => '2026-08-01', '--delay' => 250000],
            'description' => 'Repairs the prior 14 days every morning; larger historical recovery runs remain CLI-only.',
            'schedule' => 'Daily at 06:45 for recent gaps; manual CLI for larger ranges',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
            'runnable' => false,
        ],
        [
            'title' => 'compute:mf-returns',
            'command' => 'compute:mf-returns',
            'args' => [],
            'description' => 'Computes missing mutual-fund performance values after a NAV backfill.',
            'schedule' => 'Manual maintenance / CLI only',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
            'runnable' => false,
        ],
        [
            'title' => 'equities:sync-metadata',
            'command' => 'equities:sync-metadata',
            'args' => [],
            'description' => 'Syncs equity metadata from AMFI and NSE sources.',
            'schedule' => 'Daily at 08:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-upstox-instruments',
            'command' => 'equities:sync-upstox-instruments',
            'args' => [],
            'description' => 'Downloads the daily Upstox equity master and fills missing company and security metadata.',
            'schedule' => 'Daily at 06:15',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-fundamentals',
            'command' => 'equities:sync-fundamentals',
            'args' => [],
            'description' => 'Syncs daily equity fundamentals from the API.',
            'schedule' => 'Daily at 20:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-global-instruments',
            'command' => 'market:sync-global-instruments',
            'args' => [],
            'description' => 'Downloads and synchronizes the global indices and economic indicators master.',
            'schedule' => 'Daily at 06:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-company-fundamentals',
            'command' => 'market:sync-company-fundamentals',
            'args' => ['--limit' => 25, '--delay' => 250],
            'description' => 'Synchronizes complete company fundamentals in oldest-first batches.',
            'schedule' => 'Daily at 02:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-company-profiles',
            'command' => 'market:sync-company-fundamentals',
            'args' => ['--dataset' => ['profile'], '--missing-profile' => true, '--limit' => 250, '--delay' => 200],
            'description' => 'Fills missing stock sector, industry, and company-description details from Upstox profiles.',
            'schedule' => 'Daily at 02:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-upstox-quotes (Stocks)',
            'command' => 'market:sync-upstox-quotes',
            'args' => ['--type' => 'stocks', '--mode' => 'ltp'],
            'description' => 'Constantly fetches and stores live Upstox LTP quotes for actively traded equities/stocks every minute during market hours.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-quotes (Bonds & Debentures)',
            'command' => 'market:sync-upstox-quotes',
            'args' => ['--type' => 'bonds', '--mode' => 'ltp', '--once-daily' => true],
            'description' => 'Syncs bonds, debentures, and fixed-income quotes once daily after market closing.',
            'schedule' => 'Daily at 18:00 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-news',
            'command' => 'market:sync-upstox-news',
            'args' => ['--batch-size' => 30, '--max-batches' => 20],
            'description' => 'Rotates through active stock instruments and fetches up to 20 news batches per run.',
            'schedule' => 'Hourly from 07:00 to 23:00 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-events',
            'command' => 'market:sync-upstox-events',
            'args' => ['--limit' => 500, '--delay' => 200],
            'description' => 'Rotates through active equities hourly and synchronizes every corporate-action type while retaining failures for retry.',
            'schedule' => 'Hourly',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:rewrite-news',
            'command' => 'market:rewrite-news',
            'args' => ['--limit' => 2],
            'description' => 'Rewrites and verifies a quota-safe news batch, then queues valid drafts for admin approval.',
            'schedule' => 'Every 30 minutes at :05 and :35',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'exchange-calendar:sync',
            'command' => 'exchange-calendar:sync',
            'args' => [],
            'description' => 'Synchronizes the combined NSE/BSE holiday, weekend, and Muhurat calendar.',
            'schedule' => 'Daily at 06:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:repair-performance-values',
            'command' => 'market:repair-performance-values',
            'args' => [],
            'description' => 'Repairs equity and index historical performance values.',
            'schedule' => 'Manual one-time maintenance run',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
    ],
];
