<?php

return [
    'jobs' => [
        [
            'title' => 'currency:fetch-rates',
            'command' => 'currency:fetch-rates',
            'args' => [],
            'description' => 'Fetches latest USD/INR currency exchange rates via Frankfurt API.',
            'schedule' => 'Daily at 20:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync',
            'command' => 'equities:sync',
            'args' => [],
            'description' => 'Syncs equity OHLCV price data from NSE/BSE.',
            'schedule' => 'Daily at 19:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'indices:sync',
            'command' => 'indices:sync',
            'args' => [],
            'description' => 'Syncs market index prices, overview data, and holdings.',
            'schedule' => 'Daily at 19:15; maintenance refreshes can also run manually',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'sync:mf-daily',
            'command' => 'sync:mf-daily',
            'args' => ['--force' => true],
            'description' => 'Syncs mutual fund NAVs in both scheduled publication windows.',
            'schedule' => 'Daily at 21:30 and 23:15',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'mf:sync',
            'command' => 'mf:sync',
            'args' => ['--force' => true],
            'description' => 'Runs the mutual fund NAV synchronization manually or from another command.',
            'schedule' => 'Manual / invoked by orchestrators',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'mf:sync-and-calculate',
            'command' => 'mf:sync-and-calculate',
            'args' => [],
            'description' => 'Syncs mutual fund NAVs and computes performance returns.',
            'schedule' => 'Daily at 23:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-metadata',
            'command' => 'equities:sync-metadata',
            'args' => [],
            'description' => 'Syncs equity metadata from AMFI and NSE sources.',
            'schedule' => 'Daily at 08:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-fundamentals',
            'command' => 'equities:sync-fundamentals',
            'args' => [],
            'description' => 'Syncs daily equity fundamentals from the API.',
            'schedule' => 'Daily at 20:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:fetch-live',
            'command' => 'market:fetch-live',
            'args' => ['--allow-partial' => true],
            'description' => 'Fetches and stores the latest NSE/BSE quote snapshots.',
            'schedule' => 'Every 15 minutes on weekdays, 09:15-16:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'exchange-calendar:sync',
            'command' => 'exchange-calendar:sync',
            'args' => [],
            'description' => 'Synchronizes the combined NSE/BSE holiday, weekend, and Muhurat calendar.',
            'schedule' => 'Daily at 06:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:repair-performance-values',
            'command' => 'market:repair-performance-values',
            'args' => [],
            'description' => 'Repairs equity and index historical performance values.',
            'schedule' => 'Manual one-time maintenance run',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
    ],
];
