<?php

return [
    'jobs' => [
        [
            'title' => 'currency:fetch-rates',
            'command' => 'currency:fetch-rates',
            'args' => [],
            'description' => 'Fetches latest USD/INR currency exchange rates via Frankfurt API.',
            'schedule' => 'Daily at 20:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync',
            'command' => 'equities:sync',
            'args' => [],
            'description' => 'Syncs equity OHLCV price data from NSE/BSE.',
            'schedule' => 'Daily at 19:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'indices:sync',
            'command' => 'indices:sync',
            'args' => [],
            'description' => 'Syncs market index prices, overview data, and holdings.',
            'schedule' => 'Daily at 19:15; maintenance refreshes can also run manually',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'sync:mf-daily',
            'command' => 'sync:mf-daily',
            'args' => ['--force' => true],
            'description' => 'Syncs mutual fund NAVs in both scheduled publication windows.',
            'schedule' => 'Daily at 21:30 and 23:15',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'mf:sync',
            'command' => 'mf:sync',
            'args' => ['--force' => true],
            'description' => 'Runs the mutual fund NAV synchronization manually or from another command.',
            'schedule' => 'Manual / invoked by orchestrators',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'mf:sync-and-calculate',
            'command' => 'mf:sync-and-calculate',
            'args' => [],
            'description' => 'Syncs mutual fund NAVs and computes performance returns.',
            'schedule' => 'Daily at 23:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-metadata',
            'command' => 'equities:sync-metadata',
            'args' => [],
            'description' => 'Syncs equity metadata from AMFI and NSE sources.',
            'schedule' => 'Daily at 08:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'equities:sync-fundamentals',
            'command' => 'equities:sync-fundamentals',
            'args' => [],
            'description' => 'Syncs daily equity fundamentals from the API.',
            'schedule' => 'Daily at 20:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-global-instruments',
            'command' => 'market:sync-global-instruments',
            'args' => [],
            'description' => 'Downloads and synchronizes the global indices and economic indicators master.',
            'schedule' => 'Daily at 06:30',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-company-fundamentals',
            'command' => 'market:sync-company-fundamentals',
            'args' => ['--limit' => 25, '--delay' => 250],
            'description' => 'Synchronizes complete company fundamentals in oldest-first batches.',
            'schedule' => 'Daily at 02:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:ensure-upstox-token',
            'command' => 'market:ensure-upstox-token',
            'args' => [],
            'description' => 'Requests an approved replacement when the stored Upstox access token has expired.',
            'schedule' => 'Daily at 04:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:sync-upstox-quotes (Stocks)',
            'command' => 'market:sync-upstox-quotes',
            'args' => ['--type' => 'stocks', '--mode' => 'ltp'],
            'description' => 'Constantly fetches and stores live Upstox LTP quotes for actively traded equities/stocks every minute during market hours.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-quotes (Bonds & Debentures)',
            'command' => 'market:sync-upstox-quotes',
            'args' => ['--type' => 'bonds', '--mode' => 'ltp', '--once-daily' => true],
            'description' => 'Syncs bonds, debentures, and fixed-income quotes once daily after market closing.',
            'schedule' => 'Daily at 18:00 on weekdays (After market close)',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-news',
            'command' => 'market:sync-upstox-news',
            'args' => ['--batch-size' => 30, '--limit' => 60],
            'description' => 'Fetches latest breaking news for equities from Upstox News API.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-events',
            'command' => 'market:sync-upstox-events',
            'args' => ['--limit' => 25],
            'description' => 'Fetches corporate events, AGM/EGM, and dividends separately from Upstox.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-splits',
            'command' => 'market:sync-upstox-splits',
            'args' => ['--limit' => 25],
            'description' => 'Fetches stock split actions separately from Upstox Corporate Actions API.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'market:sync-upstox-bonuses',
            'command' => 'market:sync-upstox-bonuses',
            'args' => ['--limit' => 25],
            'description' => 'Fetches bonus share issues separately from Upstox Corporate Actions API.',
            'schedule' => 'Every minute on weekdays, 09:15-15:30 IST',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
        [
            'title' => 'exchange-calendar:sync',
            'command' => 'exchange-calendar:sync',
            'args' => [],
            'description' => 'Synchronizes the combined NSE/BSE holiday, weekend, and Muhurat calendar.',
            'schedule' => 'Daily at 06:00',
            'timezone' => 'Asia/Kolkata',
            'overlap' => true,
        ],
        [
            'title' => 'market:repair-performance-values',
            'command' => 'market:repair-performance-values',
            'args' => [],
            'description' => 'Repairs equity and index historical performance values.',
            'schedule' => 'Manual one-time maintenance run',
            'timezone' => 'Asia/Kolkata',
            'overlap' => false,
        ],
    ],
];
