<?php

namespace App\Support;

use App\Models\User;
use Illuminate\Http\Request;

class InternalAdminApiTester
{
    /**
     * Detect requests generated by the internal admin API tester only.
     */
    public static function isActive(Request $request, ?User $user = null): bool
    {
        $user ??= $request->user();

        if (! $user?->is_admin) {
            return false;
        }

        return $request->headers->get('X-Admin-Api-Tester') === '1'
            || $request->server->get('HTTP_X_ADMIN_API_TESTER') === '1';
    }
}
