<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class EquityPrice extends Model
{
    use HasFactory;

    protected $fillable = [
        'equity_id',
        'isin',
        'traded_date',
        'nse_open',
        'nse_high',
        'nse_low',
        'nse_close',
        'nse_last',
        'nse_prev_close',
        'nse_volume',
        'nse_turnover',
        'nse_trades',
        'nse_avg_price',
        'bse_open',
        'bse_high',
        'bse_low',
        'bse_close',
        'bse_last',
        'bse_prev_close',
        'bse_volume',
        'bse_turnover',
        'bse_trades',
        'bse_avg_price',
        'nse_chg_1d',
        'nse_chg_3d',
        'nse_chg_7d',
        'nse_chg_1m',
        'nse_chg_3m',
        'nse_chg_6m',
        'nse_chg_9m',
        'nse_chg_1y',
        'nse_chg_3y',
        'bse_chg_1d',
        'bse_chg_3d',
        'bse_chg_7d',
        'bse_chg_1m',
        'bse_chg_3m',
        'bse_chg_6m',
        'bse_chg_9m',
        'bse_chg_1y',
        'bse_chg_3y',
        'spread',
        'nse_gap_pct',
        'bse_gap_pct',
        'nse_intraday_chg_pct',
        'bse_intraday_chg_pct',
        'nse_range_pct',
        'bse_range_pct',
        'nse_avg_ticket_size',
        'bse_avg_ticket_size',
    ];

    protected $casts = [
        'traded_date' => 'date',
        'nse_open' => 'decimal:2',
        'nse_high' => 'decimal:2',
        'nse_low' => 'decimal:2',
        'nse_close' => 'decimal:2',
        'nse_prev_close' => 'decimal:2',
        'nse_turnover' => 'decimal:2',
        'nse_avg_price' => 'decimal:2',
        'nse_trades' => 'integer',
        'nse_volume' => 'integer',
        'bse_open' => 'decimal:2',
        'bse_high' => 'decimal:2',
        'bse_low' => 'decimal:2',
        'bse_close' => 'decimal:2',
        'bse_prev_close' => 'decimal:2',
        'bse_turnover' => 'decimal:2',
        'bse_avg_price' => 'decimal:2',
        'bse_trades' => 'integer',
        'bse_volume' => 'integer',
        'nse_chg_1d' => 'decimal:2',
        'nse_chg_3d' => 'decimal:2',
        'nse_chg_7d' => 'decimal:2',
        'nse_chg_1m' => 'decimal:2',
        'nse_chg_3m' => 'decimal:2',
        'nse_chg_6m' => 'decimal:2',
        'nse_chg_9m' => 'decimal:2',
        'nse_chg_1y' => 'decimal:2',
        'nse_chg_3y' => 'decimal:2',
        'bse_chg_1d' => 'decimal:2',
        'bse_chg_3d' => 'decimal:2',
        'bse_chg_7d' => 'decimal:2',
        'bse_chg_1m' => 'decimal:2',
        'bse_chg_3m' => 'decimal:2',
        'bse_chg_6m' => 'decimal:2',
        'bse_chg_9m' => 'decimal:2',
        'bse_chg_1y' => 'decimal:2',
        'bse_chg_3y' => 'decimal:2',
        'spread' => 'decimal:2',
        'nse_gap_pct' => 'decimal:2',
        'bse_gap_pct' => 'decimal:2',
        'nse_intraday_chg_pct' => 'decimal:2',
        'bse_intraday_chg_pct' => 'decimal:2',
        'nse_range_pct' => 'decimal:2',
        'bse_range_pct' => 'decimal:2',
        'nse_avg_ticket_size' => 'decimal:2',
        'bse_avg_ticket_size' => 'decimal:2',
    ];

    public function equity()
    {
        return $this->belongsTo(Equity::class);
    }
}
